/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2acd6693-d94f-4c89-8843-f63019a157a8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_v10oEpK2J",
    "aws_user_pools_web_client_id": "5t1ppmetl0b9mvj62rr9l9tch5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://p3x6mxgsy5eitol336bpznlyam.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
