/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:67d6c92c-09a6-4f42-ad97-3c728de0c3b0",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_JY5kDdNvG",
    "aws_user_pools_web_client_id": "405pkn81519agfvd6mh13clvlr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qmkq6gxqzndg3i3bss3okb6grq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
